Force monaco-editor 0.54
GreatHall [pacman.full.................] Err:  Webpack prod-server error: Error: Cannot find module 'vs/editor/editor.worker'
                                               Require stack:
                                               - /mnt/tux/devel/nixdev/sysroot/xcraft/node_modules/monaco-editor-webpack-plugin/out/index.js
                                               - /mnt/tux/devel/nixdev/sysroot/xcraft/lib/goblin-webpack/lib/webpack-config.js
                                               - /mnt/tux/devel/nixdev/sysroot/xcraft/lib/goblin-webpack/lib/prod-server.js
                                                   at Function._resolveFilename (node:internal/modules/cjs/loader:1365:15)
                                                   at Function.resolve (node:internal/modules/helpers:145:19)
                                                   at resolveMonacoPath (/mnt/tux/devel/nixdev/sysroot/xcraft/node_modules/
                                               monaco-editor-webpack-plugin/out/index.js:30:20)
                                                   at getWorkerFilename (/mnt/tux/devel/nixdev/sysroot/xcraft/node_modules/
                                               monaco-editor-webpack-plugin/out/index.js:37:34)
                                                   at /mnt/tux/devel/nixdev/sysroot/xcraft/node_modules/monaco-editor-webpack-plugin/out/
                                               index.js:136:77
                                                   at Array.map (<anonymous>)
                                                   at createLoaderRules (/mnt/tux/devel/nixdev/sysroot/xcraft/node_modules/
                                               monaco-editor-webpack-plugin/out/index.js:136:43)
                                                   at MonacoEditorWebpackPlugin.apply (/mnt/tux/devel/nixdev/sysroot/xcraft/node_modules/
                                               monaco-editor-webpack-plugin/out/index.js:100:23)
                                                   at createCompiler (/mnt/tux/devel/nixdev/sysroot/xcraft/node_modules/webpack/lib/webpack.js:97:12)
                                                   at create (/mnt/tux/devel/nixdev/sysroot/xcraft/node_modules/webpack/lib/webpack.js:187:15) //
                                               16:19:33
   peon [webpack.pack/service..........] Err:   Webpack prod-server error: Error: Cannot find module 'vs/editor/editor.worker'  // 16:19:33